CREATE DATABASE IF NOT EXISTS maaran_cars;
USE maaran_cars;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    phone VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('buyer', 'seller', 'admin') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Replace the hash below with one generated by Werkzeug before using production credentials.
-- INSERT INTO users (full_name, email, password_hash, role)
-- VALUES ('Maaran Cars Admin', 'admin@example.com', 'paste-generated-hash-here', 'admin');

CREATE TABLE IF NOT EXISTS buyer_registrations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    registration_id VARCHAR(24) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL,
    name VARCHAR(120) NOT NULL,
    place VARCHAR(120),
    requirement TEXT NOT NULL,
    budget VARCHAR(80),
    car_seen VARCHAR(160),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seller_registrations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    registration_id VARCHAR(24) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    car_name VARCHAR(120) NOT NULL,
    car_model VARCHAR(120) NOT NULL,
    car_variant VARCHAR(120),
    year VARCHAR(10),
    fuel VARCHAR(40),
    transmission VARCHAR(40),
    ownership VARCHAR(40),
    km_driven VARCHAR(40),
    insurance VARCHAR(80),
    place VARCHAR(120),
    expecting_price VARCHAR(80),
    dents VARCHAR(20),
    scratches VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
